name: build-and-push-image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  en-build-and-push-image:
    uses: ./.github/workflows/docker-publish-template.yml
    with:
      SPACY_MODEL: en_core_web_lg
      LANG: en
  it-build-and-push-image:
    uses: ./.github/workflows/docker-publish-template.yml
    with:
      SPACY_MODEL: it_core_news_lg
      LANG: it