name: build-and-push-image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  en-build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish-template.yml
    with:
      SPACY_MODEL: en_core_web_lg
      MBART_MODEL: MRNH/mbart-english-grammar-corrector
      LANG: en
  it-build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish-template.yml
    with:
      SPACY_MODEL: it_core_news_lg
      MBART_MODEL: MRNH/mbart-italian-grammar-corrector
      LANG: it